### ISSUE TITLE
Problem using signature dashlet on dashboard

### ISSUE THREAD

**Issue by afiorentini** [rouxemmanuel/DigitalSigning#12]
I put signature dashlet on my dashboard, but I obtain this error:

An error has occured in the Share component: /share/service/components/dashlets/digitalSigning/signature.
It responded with a status of 500 - Internal Error.
Error Code Information: 500 - An error inside the HTTP server which prevented it from fulfilling the request.
Error Message: 08220000 Failed to process template org/alfresco/components/dashlets/signature.get.html.ftl
Server: Alfresco Spring WebScripts - v1.2.0 (Release 1579) schema 1.000
Time: 22-set-2015 14.38.41
Click here to view full technical information on the error.
Exception: freemarker.core.InvalidReferenceException - on line 9, column 4 in org/alfresco/components/dashlets/signature.get.html.ftl script not found.

**Comment by rouxemmanuel** [comment]
Hello,

Your error seems to be linked to a bad deployment of the Share AMP because the error cause is "Exception: freemarker.core.InvalidReferenceException - on line 9, column 4 in org/alfresco/components/dashlets/signature.get.html.ftl script not found". 

So the file "components/dashlets/signature.js" is missing in the share.war (and also in the folder "share").

Could you deploy again the share AMP in the share.war, test again and go back to me ?

Regards,
Emmanuel

**Comment by afiorentini** [comment]
I uninstalled AMP and reinstall it.
The installation works without problem but I have the same error in my dashboard

Regards
Alberto

**Comment by rouxemmanuel** [comment]
Hi,

Can you test again with the lastest release (2.1.0) ?

Regards,
Emmanuel
